### ISSUE TITLE
Enhance the Go-Report card

### ISSUE THREAD

**Issue by owulveryck** [owulveryck/onnx-go#130]
_Note:_ This is a (brilliant) idea from @Pisush 

Take a look at the [Go Report Card](https://goreportcard.com/report/github.com/owulveryck/onnx-go) of the project, and submit a PR to get a better score.

**Comment by coip** [comment]
#134 is a few points back from the `ineffassign` hit

**Comment by owulveryck** [comment]
Go-report card is 100% I am closing this issue.
Many thanks to all of the contributors. You rock!
