### ISSUE TITLE
Sporadic error in the reshape operation

### ISSUE THREAD

**Issue by owulveryck** [owulveryck/onnx-go#138]
From times to time, the CI fails with an error:

```
--- FAIL: TestReshape_Scalar (0.00s)
##[error]    reshape_test.go:43: Cannot reshape, bad output shape []float32{0, 1, 2, 3, 10000, 10001, 10002, 10003}
FAIL
FAIL	github.com/owulveryck/onnx-go/backend/x/gorgonnx	0.108s
```

This is to investigate.

**Comment by blackrez** [comment]
This happen again on this jobs.

https://travis-ci.com/owulveryck/onnx-go/jobs/239399874

I will try to reproduce the same build env (with go, docker and ubuntu).

**Comment by blackrez** [comment]
This is fixed, this is not a issue about build env but about how graph works.
