### ISSUE TITLE
[tests] replace testify.Assert by assert.Assert 

### ISSUE THREAD

**Issue by owulveryck** [owulveryck/onnx-go#146]
In a PR, @Arriven  introduced https://godoc.org/gotest.tools/assert
It looks that this package has fewer dependencies than the  https://github.com/stretchr/testify package that is currently used.

Less is more!

As we do not seem to use all of the power of the testify package, the project would benefit to switch to gotest.tools so it would carry fewer dependencies.

**Comment by enc** [comment]
Hi,
you are using `assert.InDeltaSlice` which is testify specific. Do you want to move and reimplement this with the test tools?

**Comment by owulveryck** [comment]
Good point!

 I realize that most values are `interfaces{}`, and that would impose a signature:

```go
func inDeltaSlice(a, b interface{}, precision float32) bool {}
```
and then playing with reflection... Do we really want to do that? I don't think so.

Or maybe, as most tests are using known values, we could use something like:
```go
func inDeltaSliceF32(a, b []float32, precision float32) bool {}
func inDeltaSliceF64(a, b []float32, precision float32) bool {}
```

and to use it with 
```go
assert(t,inDeltaSliceF32(a.([]float32), b.([]float32), 1e-6),true)
```

Or we simply drop this issue and keep on using `testify`.

WDYT?

**Comment by enc** [comment]
In the light that the saved dependencies only affect testing and do not compile into production I wouldn't mind having a bit more comfort. While the other framework is showing good potential.

**Comment by owulveryck** [comment]
Agreed. I am closing this issue.
Thanks @enc for your time.
