### ISSUE TITLE
Gorgonia backend does not handle model with several root nodes

### ISSUE THREAD

**Issue by mattn** [owulveryck/onnx-go#48]
**Is your feature request related to a problem? Please describe.**

I'm trying to run ssd using onnx-go. But error occured.

https://gist.github.com/mattn/f5aa1b96753c76075f2666235919a8f3

```
2019/05/09 11:09:55 onnx: operator  not implemented ()
```

**Describe the solution you'd like**

As far as I looked code backend/x/gorgonnx, the error seems occur at here:

https://github.com/owulveryck/onnx-go/blob/2f00eedaabe60a2092e246f6f4354385ef8f855d/backend/x/gorgonnx/graph.go#L59-L61

**Describe alternatives you've considered**

Sorry, I can't figure out what should do here.

**Comment by owulveryck** [comment]
Good catch!

The model has multiple "root" nodes which is not handled yet by the backend. This is an extract of the model rendered with netron:

![ssd](https://user-images.githubusercontent.com/11583401/57440098-aa7bdf00-7247-11e9-8029-be0d4c3008fc.png)

Two things to do:
* setting a more explicit error message
* implement the feature

**Comment by owulveryck** [comment]
I am changing the title of this issue; I have created a "[project](https://github.com/owulveryck/onnx-go/projects/3)" to follow the implementation steps to make the SSD model working.

_Note_: I have analyzed the model, and it will require a lot of effort to make it work with gorgonia.

**Comment by owulveryck** [comment]
There is a work-in-progress with the branch [issue-48](https://github.com/owulveryck/onnx-go/tree/issue-48) but it needs some more investigation.

The actual design of "gorgonnx" does not handle operators with multiple output.

the signature of the apply method will probably require some changes:

```go
type operator interface {
        // apply analyse the graph to find the children of the node
        // then extract its gorgonia.Node references
        // and assign the result of the operation to the node n
        apply(g *Graph, n *Node) error
        // init the operator with name and attributes as carried by the onnx.Operator
        init(o onnx.Operation) error
}
```

**Comment by owulveryck** [comment]
PR #115 fixes this error, but it introduce a breaking change.
The `OperationCarrier` interface needed to be changed to handle nodes with multiple output.

https://github.com/owulveryck/onnx-go/blob/f9baf807b0137fe165253134049d23f67773ebb3/backend.go#L19-L27

This will require to change any backend implementation.
As far as I know, the only backend implemented so far is Gorgonia (via gorgonnx), and it has been patched.
